# Generated by Django 3.2.9 on 2021-12-21 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('route', models.TextField(blank=True, max_length=3000)),
                ('map_link', models.TextField(blank=True, max_length=3000)),
                ('place_Img1', models.ImageField(blank=True, null=True, upload_to='')),
                ('place_Img2', models.ImageField(blank=True, null=True, upload_to='')),
                ('place_Img3', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomtype', models.CharField(max_length=20)),
                ('beds', models.CharField(max_length=20)),
                ('baths', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('guests', models.IntegerField()),
                ('amenities', models.TextField(blank=True, max_length=3000)),
                ('facilities', models.TextField(blank=True, max_length=3000)),
                ('room_Img1', models.ImageField(blank=True, null=True, upload_to='')),
                ('room_Img2', models.ImageField(blank=True, null=True, upload_to='')),
                ('room_Img3', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ResturantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('resturantName', models.CharField(choices=[('Sultans_Dine', 'Sultans Dine'), ('Pizza_Hut', 'Pizza Hut'), ('Chillox', 'Chillox'), ('Khanas', 'Khanas'), ('Burger_King', 'Burger King'), ('Kacchi_Vai', 'Kacchi Vai')], default=None, max_length=100, null=True)),
                ('review', models.TextField(blank=True, max_length=3000)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Trash'), (2, '2- Horrible'), (3, '3- Terrible'), (4, '4- Bad'), (5, '5- OK'), (6, '6- Rideable'), (7, '7- Good'), (8, '8- Very good'), (9, '9- Perfect'), (10, '10- Best')], null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('placeName', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Cox-Bazar', 'Cox-Bazar'), ('Sylhet', 'Sylhet'), ('Cumilla', 'Cumilla'), ('Gazipur', 'Gazipur'), ('Rajshahi', 'Rajshahi')], default=None, max_length=100, null=True)),
                ('review', models.TextField(blank=True, max_length=3000)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Trash'), (2, '2- Horrible'), (3, '3- Terrible'), (4, '4- Bad'), (5, '5- OK'), (6, '6- Rideable'), (7, '7- Good'), (8, '8- Very good'), (9, '9- Perfect'), (10, '10- Best')], null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hotelName', models.CharField(choices=[('Pan_Pacific_Sonargoan', 'Pan Pacific Sonargoan'), ('Radisson_Blu', 'Radisson Blu'), ('Hotel_De_Meridian', 'Hotel De Meridian'), ('Grand_Plaza_Hotel', 'Grand Plaza Hotel'), ('Empyrean_Hotel', 'Empyrean Hotel'), ('The_Raintree_Dhaka', 'The Raintree Dhaka')], default=None, max_length=100, null=True)),
                ('review', models.TextField(blank=True, max_length=3000)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Trash'), (2, '2- Horrible'), (3, '3- Terrible'), (4, '4- Bad'), (5, '5- OK'), (6, '6- Rideable'), (7, '7- Good'), (8, '8- Very good'), (9, '9- Perfect'), (10, '10- Best')], null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=30)),
                ('user_phone', models.CharField(max_length=20)),
                ('checkin_date', models.CharField(max_length=20)),
                ('checkout_date', models.CharField(max_length=20)),
                ('hotel_name', models.CharField(max_length=20)),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(max_length=20)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
