# Generated by Django 3.2.6 on 2021-08-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_balaka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balaka',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Trash'), (2, '2- Horrible'), (3, '3- Terrible'), (4, '4- Bad'), (5, '5- OK'), (6, '6- Rideable'), (7, '7- Good'), (8, '8- Very good'), (9, '9- Perfect'), (10, '10- Best')], null=True),
        ),
    ]
