# Generated by Django 3.2.9 on 2021-12-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('route', models.TextField(blank=True, max_length=3000)),
                ('map_link', models.TextField(blank=True, max_length=3000)),
                ('place_Img1', models.ImageField(blank=True, null=True, upload_to='')),
                ('place_Img2', models.ImageField(blank=True, null=True, upload_to='')),
                ('place_Img3', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
