# Generated by Django 3.2.9 on 2021-12-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResturantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('address', models.TextField(blank=True, max_length=3000)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('menu', models.TextField(blank=True, max_length=3000)),
                ('website', models.CharField(max_length=500)),
                ('res_img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='placereview',
            name='placeName',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Cox_Bazar', 'Cox-Bazar'), ('Sylhet', 'Sylhet'), ('Cumilla', 'Cumilla'), ('Gazipur', 'Gazipur'), ('Rajshahi', 'Rajshahi')], default=None, max_length=100, null=True),
        ),
    ]
