# Generated by Django 3.2.6 on 2021-12-24 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20211221_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturantreview',
            name='resturantName',
            field=models.CharField(choices=[('Istanbul_Restaurant', 'Istanbul Restaurant'), ('The_Dining_Lounge', 'The Dining Lounge'), ('Sultans_Dine', 'Sultans Dine'), ('Pizza_Hut', 'Pizza Hut'), ('Chillox', 'Chillox'), ('Khanas', 'Khanas'), ('Burger_King', 'Burger King'), ('Kacchi_Vai', 'Kacchi Vai')], default=None, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=300, null=True)),
                ('user_phone', models.CharField(max_length=20, null=True)),
                ('user_address', models.CharField(max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bio', models.CharField(max_length=300, null=True)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
