# Generated by Django 3.2.6 on 2021-08-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_balaka_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balaka',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
