# Generated by Django 3.2.6 on 2021-09-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210905_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='usernoti',
            new_name='user',
        ),
    ]
