# Generated by Django 3.2.6 on 2021-12-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wishlist',
        ),
    ]
