# Generated by Django 3.2.6 on 2021-12-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='PlaceName',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Cox_Bazar', 'Cox-Bazar'), ('Sylhet', 'Sylhet'), ('Cumilla', 'Cumilla'), ('Gazipur', 'Gazipur'), ('Rajshahi', 'Rajshahi')], default=None, max_length=100, null=True, unique=True),
        ),
    ]
