# Generated by Django 3.2.6 on 2021-12-29 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_alter_wishlist_placename'),
    ]

    operations = [
        migrations.CreateModel(
            name='userBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Cox_Bazar', 'Cox-Bazar'), ('Sylhet', 'Sylhet'), ('Cumilla', 'Cumilla'), ('Gazipur', 'Gazipur'), ('Rajshahi', 'Rajshahi')], default=None, max_length=100, null=True, unique=True)),
                ('text', models.TextField(blank=True, max_length=3000)),
                ('place_Img1', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
