# Generated by Django 3.2.9 on 2021-12-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_resturantreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomtype', models.CharField(max_length=20)),
                ('beds', models.CharField(max_length=20)),
                ('baths', models.CharField(max_length=20)),
                ('guests', models.IntegerField()),
                ('amenities', models.TextField(blank=True, max_length=3000)),
                ('facilities', models.TextField(blank=True, max_length=3000)),
            ],
        ),
    ]
