# Generated by Django 3.2.9 on 2021-12-18 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_resturantreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=30)),
                ('user_phone', models.CharField(max_length=20)),
                ('checkin_date', models.CharField(max_length=20)),
                ('checkout_date', models.CharField(max_length=20)),
                ('hotel_name', models.CharField(max_length=20)),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(max_length=20)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
