# Generated by Django 3.2.9 on 2021-12-19 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_hotelreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('placeName', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Cox-Bazar', 'Cox-Bazar'), ('Sylhet', 'Sylhet'), ('Cumilla', 'Cumilla'), ('Gazipur', 'Gazipur'), ('Rajshahi', 'Rajshahi')], default=None, max_length=100, null=True)),
                ('review', models.TextField(blank=True, max_length=3000)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Trash'), (2, '2- Horrible'), (3, '3- Terrible'), (4, '4- Bad'), (5, '5- OK'), (6, '6- Rideable'), (7, '7- Good'), (8, '8- Very good'), (9, '9- Perfect'), (10, '10- Best')], null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
