# Generated by Django 3.2.6 on 2021-12-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_userblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='Title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
