# Generated by Django 3.2.9 on 2021-12-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211219_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
