# Generated by Django 3.2.6 on 2021-12-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_userblog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
