# Generated by Django 3.2.9 on 2021-12-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_room_img32_roommodel_room_img321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommodel',
            old_name='room_Img321',
            new_name='room_Img3',
        ),
    ]
