# Generated by Django 3.2.6 on 2021-12-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_userblog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='Title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
