# Generated by Django 3.2.9 on 2021-12-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_roommodel_room_img1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='room_Img2',
            field=models.ImageField(default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='room_Img3',
            field=models.ImageField(default='default.jpg', null=True, upload_to=''),
        ),
    ]
