# Generated by Django 3.2.9 on 2021-12-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_room_img321_roommodel_room_img3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelreview',
            name='hotelName',
            field=models.CharField(choices=[('Pan_Pacific_Sonargoan', 'Pan Pacific Sonargoan'), ('Radisson_Blu', 'Radisson Blu'), ('Hotel De Meridian', 'Hotel De Meridian'), ('Grand Plaza Hotel', 'Grand Plaza Hotel'), ('Empyrean Hotel', 'Empyrean Hotel'), ('The Raintree Dhaka', 'The Raintree Dhaka')], default=None, max_length=100, null=True),
        ),
    ]
