# Generated by Django 3.2.6 on 2021-12-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_appreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='media'),
        ),
    ]
