# Generated by Django 3.2.9 on 2021-12-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20211219_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='room_Img1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='room_Img2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='room_Img3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
