# Generated by Django 3.2.9 on 2021-12-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20211220_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='map_link',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='place',
            name='route',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
