# Generated by Django 3.2.9 on 2021-12-20 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_place'),
        ('main', '0021_auto_20211220_2246'),
    ]

    operations = [
    ]
