# Generated by Django 3.2.9 on 2021-12-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_merge_0018_place_0021_auto_20211220_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelreview',
            name='hotelName',
            field=models.CharField(choices=[('Pan_Pacific_Sonargoan', 'Pan Pacific Sonargoan'), ('Radisson_Blu', 'Radisson Blu'), ('Hotel_De_Meridian', 'Hotel De Meridian'), ('Grand_Plaza_Hotel', 'Grand Plaza Hotel'), ('Empyrean_Hotel', 'Empyrean Hotel'), ('The_Raintree_Dhaka', 'The Raintree Dhaka')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resturantreview',
            name='resturantName',
            field=models.CharField(choices=[('Sultans_Dine', 'Sultans Dine'), ('Pizza_Hut', 'Pizza Hut'), ('Chillox', 'Chillox'), ('Khanas', 'Khanas'), ('Burger_King', 'Burger King'), ('Kacchi_Vai', 'Kacchi Vai')], default=None, max_length=100, null=True),
        ),
    ]
